# Generated by Django 3.2.12 on 2023-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=None, max_length=80, null=True),
        ),
    ]
