# Generated by Django 3.2.12 on 2023-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labservice',
            name='city_service',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
