# Generated by Django 3.2.12 on 2023-03-10 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_result_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Notification!')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('notification_appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifaction_appointment', to='users.appointment')),
                ('notification_lab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_lab', to='users.lab')),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
